spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:19091'
              - 'http://localhost:19092'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
