server:
  port: 19091
spring:
  profiles:
    default: dev
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: service
          uri: lb://service
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/service/v3/api-docs
        name: Team Blue Service API 문서
      - url: /api/auth/v3/api-docs
        name: Team Blue Auth API 문서
  api-docs:
    enabled: true

service:
  jwt:
    secret-key: # JWT 시크릿 키
